const crc32 = require("crc/crc32");
const { format } = require("date-fns");
const { tokenExpiresDays } = require("./defaults");

// userTemplate, tokenTemplate files will be taken from json folder generated by INIT feature
// const { fetchFile } = require("./utils-fs");
const { tokenTemplate, userTemplate } = require("./template");

const createToken = async (data) => {
  const ttlArr = getTokenLifeSpan(tokenExpiresDays);
  const tokenObj = {
    ...userTemplate,
    ...tokenTemplate,
  };

  tokenObj.username = data;
  tokenObj.token = crc32(data);
  tokenObj.created = ttlArr[0];
  tokenObj.expires = ttlArr[1];
  console.log(JSON.stringify(tokenObj));
};

const getTokenLifeSpan = (ttlDays) => {
  const createdDate = Date.now();
  const expiresDate = new Date();

  expiresDate.setDate(expiresDate.getDate() + ttlDays);
  return [createdDate, expiresDate].map((item) => format(item, "dd/MM/yyyy"));
};

module.exports = {
  createToken,
};
